apiVersion: v1
kind: ConfigMap
metadata:
  name: invoicing-urls
data:
  identity-service-base-url: https://id.invoicing.sdsoftware.be
  frontend-callback-url: https://invoicing.sdsoftware.be/auth/callback
  frontend-base-url: https://invoicing.sdsoftware.be
  customer-api-base-url: https://api.customer.invoicing.sdsoftware.be
