@baseUrl = http://127.0.0.1:8000

@id = 9bfed7e4-91d5-49ea-86de-004e1b8df903

### createInvoice request

POST {{baseUrl}}/sdsoftware/invoices
Content-Type: application/json

{
  "customerName": "Cummerata Inc",
  "streetAndNumber": "1234 Main St",
  "postalCode": "12345",
  "city": "New York",
  "country": "USA",
  "vatNumber": "123456789"
}

### getInvoice request

GET {{baseUrl}}/sdsoftware/invoices/{{id}}

### addInvoiceLine request

POST {{baseUrl}}/sdsoftware/invoices/{{id}}/lines
Content-Type: application/json

{
  "description": "Test",
  "quantity": 1,
  "unitPrice": 100,
  "vatPercentage": 21
}

### finalizeInvoice request

PATCH {{baseUrl}}/sdsoftware/invoices/{{id}}/finalize

### getInvoicePdf request

GET {{baseUrl}}/sdsoftware/invoices/{{id}}/pdf
