version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 16-bullseye

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - backend
      - frontend
      
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0

    ports:
      - "3000:3000"

    depends_on:
      - storage
      - db
    

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  storage:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: unless-stopped
    volumes:
      - storage-data:/data
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # Add "forwardPorts": ["10000", "10001"] to **devcontainer.json** to forward Azurite locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    networks:
      - backend
      
  db:
    hostname: db.local
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    mem_limit: 3g
    cpu_count: 2
    
    ports: 
      - "8081:8081"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
      
    environment:
        AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 10
        AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
        
    networks:
      backend:
        aliases:
          - db.local

volumes:
  storage-data:

networks:
  frontend:
  backend: