name: Publish website
on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build & Push docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push invoicing-identityservice to Docker Hub
        run: |
          docker build -t sanderdeclerck/invoicing-identityservice:$(echo $GITHUB_SHA | head -c7) ./src/Services/Identity/Identity.Service
          docker push sanderdeclerck/invoicing-identityservice:$(echo $GITHUB_SHA | head -c7)

      - name: Build & Push invoicing-frontend to Docker Hub
        run: |
          docker build --build-arg FONTAWESOME_NPM_AUTH_TOKEN=${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }} -t sanderdeclerck/invoicing-frontend:$(echo $GITHUB_SHA | head -c7) ./src/Web/invoicing-frontend
          docker push sanderdeclerck/invoicing-frontend:$(echo $GITHUB_SHA | head -c7)

  deploy:
    name: Deploy images to kubernetes
    runs-on: ubuntu-latest
    needs: build
    env:
      NAMESPACE: invoicing

    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Authenticate with cluster
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_K8S_CLUSTER }}

      - name: Set the correct namespace
        run: kubectl config set-context --current --namespace=$NAMESPACE

      - name: Deploy invoicing-identityservice-data.yaml
        run: kubectl apply -f ./deploy/k8s/invoicing-identityservice-data.yaml

      - name: Deploy invoicing-identityservice.yaml
        run: |
          kubectl apply -f ./deploy/k8s/invoicing-identityservice.yaml
          kubectl set image deployments/invoicing-identityservice "invoicing-identityservice=sanderdeclerck/invoicing-identityservice:$(echo $GITHUB_SHA | head -c7)"
          kubectl rollout resume deployments/invoicing-identityservice

      - name: Deploy invoicing-frontend.yaml
        run: |
          kubectl apply -f ./deploy/k8s/invoicing-frontend.yaml
          kubectl set image deployments/invoicing-frontend "invoicing-frontend=sanderdeclerck/invoicing-frontend:$(echo $GITHUB_SHA | head -c7)"
          kubectl rollout resume deployments/invoicing-frontend

      - name: Deploy tls-issuer.yaml
        run: kubectl apply -f ./deploy/k8s/tls-issuer.yaml

      - name: Deploy ingress.yaml
        run: kubectl apply -f ./deploy/k8s/ingress.yaml
