name: pull-request-preview-infrastructure

on:
  pull_request:
    branches: [ main ]

jobs:
  preview-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
          
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show account id
        run: az account show --query id -o tsv
          
      - uses: pulumi/actions@v3
        with:
          command: preview
          work-dir: ./infrastructure
          stack-name: prd
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}