name: Push to master - deploy services

on: 
  pull_request:
    branches: [ main ]

jobs:
  build-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/Sdsoftware-bv/invoicing-api
          tags: |
            type=sha
            type=ref,event=branch

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/services/invoicing/Invoicing.Api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
