name: Push to master - deploy services

on: 
  pull_request:
    branches: [ main ]

jobs:
  build-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/sdsoftware-bv/invoicing-api
          flavor: latest=true
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            ${{ github.sha }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/services/invoicing/Invoicing.Api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-appservice:
    runs-on: ubuntu-latest
    needs: [build-dockerfile]

    steps:
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2

      - name: Get Azure App Service name
        run: |
          pulumi login
          pulumi stack select dev
          pulumi stack output InvoicingServiceName
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}


      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App for Container'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: invoicing-service3ee1ade6
          images: ghcr.io/sdsoftware-bv/invoicing-api:${{ github.sha }}